# =============================================================================
# Outputs - Connection strings and endpoints
# =============================================================================

# Resource Group
output "resource_group_name" {
  description = "Resource group name"
  value       = azurerm_resource_group.main.name
}

# =============================================================================
# Azure OpenAI
# =============================================================================
output "openai_endpoint" {
  description = "Azure OpenAI endpoint URL"
  value       = azurerm_cognitive_account.openai.endpoint
}

output "openai_key" {
  description = "Azure OpenAI API key"
  value       = azurerm_cognitive_account.openai.primary_access_key
  sensitive   = true
}

output "openai_deployment_chat" {
  description = "Chat model deployment name"
  value       = azurerm_cognitive_deployment.gpt4o_mini.name
}

output "openai_deployment_embedding" {
  description = "Embedding model deployment name"
  value       = azurerm_cognitive_deployment.embedding.name
}

# =============================================================================
# Azure AI Search
# =============================================================================
output "search_endpoint" {
  description = "Azure AI Search endpoint"
  value       = "https://${azurerm_search_service.main.name}.search.windows.net"
}

output "search_key" {
  description = "Azure AI Search admin key"
  value       = azurerm_search_service.main.primary_key
  sensitive   = true
}

# =============================================================================
# Storage
# =============================================================================
output "storage_connection_string" {
  description = "Storage account connection string"
  value       = azurerm_storage_account.main.primary_connection_string
  sensitive   = true
}

output "storage_account_name" {
  description = "Storage account name"
  value       = azurerm_storage_account.main.name
}

# =============================================================================
# AKS
# =============================================================================
output "aks_cluster_name" {
  description = "AKS cluster name"
  value       = azurerm_kubernetes_cluster.main.name
}

output "aks_get_credentials_command" {
  description = "Command to get AKS credentials"
  value       = "az aks get-credentials --resource-group ${azurerm_resource_group.main.name} --name ${azurerm_kubernetes_cluster.main.name}"
}

# =============================================================================
# Container Registry
# =============================================================================
output "acr_login_server" {
  description = "ACR login server"
  value       = azurerm_container_registry.main.login_server
}

output "acr_admin_username" {
  description = "ACR admin username"
  value       = azurerm_container_registry.main.admin_username
}

output "acr_admin_password" {
  description = "ACR admin password"
  value       = azurerm_container_registry.main.admin_password
  sensitive   = true
}

# =============================================================================
# Key Vault
# =============================================================================
output "key_vault_uri" {
  description = "Key Vault URI"
  value       = azurerm_key_vault.main.vault_uri
}

# =============================================================================
# Environment File Generator
# =============================================================================
output "env_file_content" {
  description = "Content for .env file (run: terraform output -raw env_file_content > ../../.env)"
  sensitive   = true
  value       = <<-EOT
# =============================================================================
# Auto-generated by Terraform - ${timestamp()}
# =============================================================================

# Azure OpenAI
AZURE_OPENAI_ENDPOINT=${azurerm_cognitive_account.openai.endpoint}
AZURE_OPENAI_API_KEY=${azurerm_cognitive_account.openai.primary_access_key}
AZURE_OPENAI_API_VERSION=2024-02-01
AZURE_OPENAI_DEPLOYMENT_NAME=${azurerm_cognitive_deployment.gpt4o_mini.name}
AZURE_OPENAI_EMBEDDING_DEPLOYMENT=${azurerm_cognitive_deployment.embedding.name}

# Azure AI Search
AZURE_SEARCH_ENDPOINT=https://${azurerm_search_service.main.name}.search.windows.net
AZURE_SEARCH_API_KEY=${azurerm_search_service.main.primary_key}
AZURE_SEARCH_INDEX_NAME=rag-documents

# Azure Storage
AZURE_STORAGE_CONNECTION_STRING=${azurerm_storage_account.main.primary_connection_string}
AZURE_STORAGE_CONTAINER=documents

# Redis (in-cluster for dev)
REDIS_URL=redis://redis:6379/0

# Application
APP_ENV=development
LOG_LEVEL=INFO

# RAG Configuration
CHUNK_SIZE=1000
CHUNK_OVERLAP=200
TOP_K_RESULTS=5
SIMILARITY_THRESHOLD=0.75
EOT
}

# =============================================================================
# Cost Summary
# =============================================================================
output "estimated_monthly_cost" {
  description = "Estimated monthly cost breakdown"
  value       = <<-EOT
  
  ╔══════════════════════════════════════════════════════════════╗
  ║              ESTIMATED MONTHLY COST (Dev Config)             ║
  ╠══════════════════════════════════════════════════════════════╣
  ║ Resource              │ SKU/Tier      │ Est. Cost            ║
  ╠═══════════════════════╪═══════════════╪══════════════════════╣
  ║ Azure OpenAI          │ S0 (pay/use)  │ ~$5-20 (usage based) ║
  ║ Azure AI Search       │ Free          │ $0                   ║
  ║ AKS (1x B2s node)     │ Free tier     │ ~$30                 ║
  ║ Container Registry    │ Basic         │ ~$5                  ║
  ║ Storage Account       │ LRS           │ ~$1                  ║
  ║ Key Vault             │ Standard      │ ~$0.03/10K ops       ║
  ║ Log Analytics         │ PerGB         │ ~$2-5                ║
  ╠═══════════════════════╧═══════════════╧══════════════════════╣
  ║ TOTAL ESTIMATED                       │ ~$45-65/month        ║
  ╚══════════════════════════════════════════════════════════════╝
  
  💡 Cost Optimization Tips:
  • Stop AKS when not in use: az aks stop --name ${azurerm_kubernetes_cluster.main.name} --resource-group ${azurerm_resource_group.main.name}
  • Start AKS when needed:   az aks start --name ${azurerm_kubernetes_cluster.main.name} --resource-group ${azurerm_resource_group.main.name}
  • Destroy all: terraform destroy
  
  EOT
}
